server:
  port: ${PROD_SERVER_PORT}
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/javascript, application/json

logging:
  level:
    ROOT: INFO
    org.example: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: ${PROD_DB_SCHEMA_NAME}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
    jpa:
      database-platform: org.hibernate.dialect.FixedPostgreSQL10Dialect
      hibernate:
        ddl-auto: update
